# This is the parameter config file for offline training of ANN models to estimate joint torques using sEMG signals.
---
  filepath:

    project_path:  '/home/dfki.uni-bremen.de/kschari/kc_ws/repos/biosignal_toolbox'
    data_path:     'data/m-rock_demo/'
    emg_path:      'emg_data/24092024_FW28D_'
    quali_path:    ['quali_data/FW28D/quali_torque_elbow_', 'quali_data/FW28D/quali_torque_front_', 'quali_data/FW28D/quali_torque_side_']
    fig_save_path: '../../plots/m-rock_demo/'



  data_param:
    weights:              ['0g', '1000g']
    mov_type:             ['complex', 'grasp']
    set_num:              ['1', '2', '3', '4', '5', '6', '7']

  workflow_param:
    mode:                 "train" # "train" or "infer"
    model_dir:            "saved_models/TCN_MTL"
    input_mode:           "time" # options: "time", "freq", "time+freq"

  preprocess_param:
    channel_names_emg:    ['BP1', 'BP2', 'BP3', 'BP4', 'BP5', 'BP6', 'BP7', 'BP8']
    channel_names_quali:  ['right', 'left', 'marker']
    window_size_x:        250  #samples
    window_size_e:        250  # Elbow Model
    window_size_s:        150 # Shoulder Side Model
    window_size_f:        150 # Shoulder Front
    window_step:          10  #samples
    feature_size:         20  #samples
    feature_select:       'end'

    f_samp:               500
    f_cutoff_hpf:         15  #cutoff freq for bandpass 
    f_cutoff_lpf:         200 #cutoff freq for bandpass 
    filter_order:         2

    f_cutoff_sm_lpf:      5   #cutoff freq for smoothing
    sm_filter_order:      4   # filter order for smoothing lpf

    filter_method:        'zero_phase'
    var_filter_width:     20
    mvc:                  1.1657004817469086e-06
      # BR07D: 4.569592924022451e-06
      # FW28D: 1.1657004817469086e-06
      # BU62D:  3.941259927517915e-06
      # WW06D: 0.09238221776255644
    act_delay:            25
    act_beta1:            0.25
    act_beta2:            0.05
    act_gamma:            0.7
    act_A:                -1.5

  model_param:
    n_epochs:             100
    batch_size:           256

    loss_fcn:             'mse' # mse
    optimizer:            'adam'

    train_test_split:     0.8
    validation_split:     0.1

    is_early_stop:        True
    monitor:              'val_loss'
    min_delta:            0.0001
    patience:             20
    verbose:              0
    baseline:             null
    restore_best_weights: True

  post_processing_param:
    savitzky_window_length: 21
    savitzky_polyorder:    3
    moving_av_window_size: 40
    savitzky_on:           False
    moving_av_on:          False

  plot_param:
    is_plot_raw:          False
    is_plot_quali:        False
    is_plot_hpf:          False
    is_plot_var_filter:   False
    is_plot_smoothed:     False
    is_plot_act:          False
    is_plot_filt_win:     False
