# This is the parameter config file for offline training of ANN models to estimate joint torques using sEMG signals.
---
  filepath:
    data_path:                'data/jte/'
    emg_path:                 'emg_data/BU62D/'
    emg_file_prefix:          '24072025_*_BU62D'
    quali_tsv_path:           'quali_data/BU62D/tsv/'
<<<<<<< HEAD
    quali_tsv_prefix:         '24_07_2025_BU62D'
    quali_path:               ['quali_data/BU62D/tsv/quali_torque_elbow_', 'quali_data/FW28D/Day1/quali_torque_front_', 'quali_data/FW28D/Day1/quali_torque_side_']
    fig_save_path:            'data/test/'
    quali_torques_save_path:  'data/jte/quali_data/BU62D/torques'
  
  data_param:
    weights:              ['0g', '1100g', '1850g']
    mov_type:             ['complex', 'grasp']
    set_num:              ['1', '2', '3']
    subject_code:         ['FW28D']
    subject_weight:       80    #weight in kg
    subject_bio_sex:      'male'
    subject_hand_len:     113  #wrist to 3rd knuckle len in mm
  
  preprocess_param:
    channel_names_emg:    ['BP1', 'BP2', 'BP3', 'BP4', 'BP5', 'BP6', 'BP7', 'BP8']
    channel_names_quali:  ['right', 'left', 'marker']
    window_size_x:        50  #samples
    window_size_y:        50  #samples
    window_step:          50  #samples
    feature_size:         20  #samples
    feature_select:       'end'
    feature_type:         'mav'

    f_samp:               500
    f_cutoff_hpf:         15  #cutoff freq for bandpass 
    f_cutoff_lpf:         200 #cutoff freq for bandpass 
    filter_order:         2

    f_cutoff_sm_lpf:      5   #cutoff freq for smoothing
    sm_filter_order:      4   # filter order for smoothing lpf

    filter_method:        'zero_phase'
    var_filter_width:     20
    mvc:                  2.7579163508176626e-06
    act_delay:            25
    act_beta1:            0.25
    act_beta2:            0.05
    act_gamma:            0.7
    act_A:                -1.5
    filter_method:        'zero_phase'
    var_filter_width:     20
    mvc:                  2.7579163508176626e-06
    act_delay:            25
    act_beta1:            0.25
    act_beta2:            0.05
    act_gamma:            0.7
    act_A:                -1.5
  
  model_param:
    n_epochs:             300
    batch_size:           25

    loss_fcn:             'mse'
    optimizer:            'nadam'
    metrics:              'mse'

    train_test_split:     0.9
    validation_split:     0.2

    is_early_stop:        True
    monitor:              'val_loss'
    min_delta:            0.01
    patience:             50
    verbose:              0
    baseline:             null
    restore_best_weights: True
    start_from_epoch:     0

    neurons_h1:           5
    neurons_h2:           2

    act_inp:              'relu'
    act_h1:               'relu'
    act_h2:               'linear' 

    is_save_model:        False
    save_model_path:      'data/m_rock/demo/zdemo_ml_models'
    load_models:          False
    is_save_model:        False
    save_model_path:      'data/m_rock/demo/zdemo_ml_models'
    load_models:          False

  post_train_param:
    eval_type:            'offline' 
    filter_type:          'mean'
    filter_size:          3    
    is_save_plot:         False
  
  plot_param:
    is_plot_raw:          False
    is_plot_quali:        False
    is_plot_hpf:          False
    is_plot_var_filter:   False
    is_plot_smoothed:     False
    is_plot_act:          False
    is_plot_filt_win:     False        
    is_plot_raw:          False
    is_plot_quali:        False
    is_plot_hpf:          False
    is_plot_var_filter:   False
    is_plot_smoothed:     False
    is_plot_act:          False
    is_plot_filt_win:     False        
=======
    quali_torque_path:        'quali_data/BU62D/torques/'
    quali_tsv_prefix:         '24_07_2025_BU62D'
    quali_torque_prefix:      ['quali_torque_elbow_24_07_2025', 'quali_torque_shoulder_front_24_07_2025', 'quali_torque_shoulder_side_24_07_2025']
    
    fig_save_path:            'data/jte/plots/'
    quali_torques_save_path:  'data/jte/quali_data/BU62D/torques'
    save_model_path:          'data/jte/ml_models/'
  
  data_param:
    # weights:                  ['0g', '1100g', '1850g']
    weights:                  ['0g']
    mov_type:                 ['complex', 'grasp']
    set_num:                  ['1', '2', '3', '4']
    subject_code:             ['BU62D']
    subject_weight:           80    #weight in kg
    subject_bio_sex:          'male'
    subject_hand_len:         113  #wrist to 3rd knuckle len mm
  
  preprocess_param:
    channel_names_emg:        ['BP1', 'BP2', 'BP3', 'BP4', 'BP5', 'BP6', 'BP7', 'BP8']
    channel_names_quali:      ['right', 'marker']
    window_size_x:            50  #samples
    window_size_y:            50  #samples
    window_step:              25  #samples

    f_samp:                   500
    f_cutoff_hpf:             15  #cutoff freq for bandpass 
    f_cutoff_lpf:             200 #cutoff freq for bandpass 
    filter_order:             2

    f_cutoff_sm_lpf:          5   #cutoff freq for smoothing
    sm_filter_order:          4   #filter order smoothing lpf

    filter_method:            'zero_phase'
    var_filter_width:         20
    mvc:                      [3.49862020e-06, 1.04643431e-07, 7.26389817e-08, 1.39860186e-07, 2.33216414e-07, 3.02970132e-07, 6.24961951e-08, 7.62761165e-08]
    normalisation_method:     'channel_wise_mvc'

    use_activation_fncn:      False
    act_delay:                25
    act_beta1:                0.25
    act_beta2:                0.05
    act_gamma:                0.7
    act_A:                    -1.5
    
  
  model_param:
    n_epochs:                 300
    batch_size:               25

    loss_fcn:                 'mse'
    optimizer:                'nadam'
    metrics:                  'mse'

    train_test_split:         0.9
    validation_split:         0.2

    is_early_stop:            True
    monitor:                  'val_loss'
    min_delta:                0.01
    patience:                 50
    verbose:                  0
    baseline:                 null
    restore_best_weights:     True
    start_from_epoch:         0

    neurons_h1:               5
    neurons_h2:               2
    neurons_out:              0

    act_h1:                   'relu'
    act_h2:                   'relu'
    act_out:                  'tanh' 

    is_save_model:            False
    load_models:              False

  post_train_param:
    eval_type:                'offline' 
    filter_type:              'mean'
    filter_size:              3    
    is_save_plot:             False
  
  plot_param:
    is_plot_raw:              False
    is_plot_quali:            False
    is_plot_hpf:              False
    is_plot_var_filter:       False
    is_plot_smoothed:         False
    is_plot_act:              False
    is_plot_filt_win:         False        
>>>>>>> 306e0a815e9ebbcf68f8bb2e035814839e083b34
